### ISSUE TITLE
the website does not show in Chrome

### ISSUE THREAD

**Issue by genccal** [pymike00/QuestionTime#9]
Hi Mike, 

I followed your udemy class. My issue was the dependence issue stemming from webpack-bundle-tracer. Having downgraded the version and updated the vue.config.js file, the same bug persists. 

Now I try to download your entire code and it still fails to run in my browser Chrome. None of URLs works. 
My browser gave me this error message.
`bundle.js:1 Failed to load resource: net::ERR_ADDRESS_INVALID`

Could you please update the source code for this project? I really like it but so far I have had no success.

**Comment by VFS** [comment]
Just finished this awesome course.

@genccal the default configuration that's on master is not production ready. As explained by @pymike00 on the last classes, you must make a small hack on your [core/views.py](https://github.com/pymike00/QuestionTime/blob/b659278dbb7b8b2f19ace9521aa9b77cb9529559/QuestionTime/core/views.py#L9) if you want to simulate the behavior of using the bundled version of your app without changing  `DEBUG = True`.

You can achieve that without changing your DEBUG flag on `settings.py` (because this causes a lot of side-effects if you don't have the correct production settings.) by inverting the behavior of the `get_template_name`, so it uses the template with the compiled `bundle.js` and `bundle.css` files even tough you are still on debug mode. To do that, edit your `core/views.py` file:
```python
    def get_template_names(self):
        if not settings.DEBUG:
            template_name = "index-dev.html"
        else:
            template_name = "index.html"
        return template_name
```
**remember to revert  back when deploying to production, else all will fail because visitors cannot access your (locally running) webpack server.**

Then, if you want to run it on a production server, you also have to setup whitenoise, and then collect all static files to be properly served. This [heroku guide](https://devcenter.heroku.com/articles/django-assets) on how to manage django assets will teach you how to do that.

**Comment by pymike00** [comment]
Hi both! 

Sorry about my late answer. 

I am not really keeping track of what's going on with this repo as it's just part of the resources for the video course itself where most implementation details are discussed, as @VFS kindly explained (thanks for doing that, it's appreciated!)

The course will soon be updated to reflect the changes imposed by the new major release of Vue JS, and I am planning to stop using the webpack-bundle-tracker / django-webpack-loader all together.

All the best and Happy Coding!
Michele
